### PR TITLE
Compiling with Rtools on Windows

### PR DESCRIPTION
**Pull request by yaccos**
Dear `cobrar` maintainers,

I have now managed to get the package to compile and run on Windows 11, Rtools44, and R 4.4.1 (2024-06-14 ucrt). Although I am unsure whether you have managed to do so yourself, I experienced that the following steps were necessary to make the approach work:

- Install `glpk` and `libsbml` inside Rtool's ucrt64 environment. Open Rtools44 Bash, then run `pacman -S mingw-w64-ucrt-x86_64-libsbml mingw-w64-ucrt-x86_64-glpk`.
- Modify `src/Makevars.win` as in this pull request. In particular, change `LIB_SBML=C:/rtools44/mingw64` to `LIB_SBML=C:/rtools44/ucrt64`, and add `-lsbml` to the end of `PKG_LIBS`.

In addition, I have some comments on the process:

- I could not get the package installed when the dependencies were installed in the mingw64 environment as was attempted in the `main` branch. The linking either failed or the symbols in the libSBML library could not be loaded. I suppose this is due to an ABI incompatibility between UCRT which is used by R and MSVCRT which is used by mingw64.
- Currently, `LIB_SBML` is a hard-coded path to `C:/rtools44/ucrt64`. While I think it will be OK require this dependency to reside inside ucrt64, hard-coding the path does provide other problems. First, we should not expect Rtools to be located inside the root of the `C:` directory, while this is usually true, I think some users have other setups. Second, Rtools44 reflects that it is supposed to work with R 4.4.x, it will not work with other (and future) versions of R. I think there should be a configuration script to pick the correct Rtools directory.
- Linking dynamically to a C++ API increases the risk of ABI compatibility problems compared  to a  C API. I don't know how big of a problem it will be in practice, but this is definately be something to watch out for.
- On Unix platforms, the `libSBML` dynamic library is used from its original folder, whereas on Windows it is copied into the package itself. The solution on Windows makes it easier to distribute binary packages at the cost of having a larger package size which triggers an `R CMD CHECK` `NOTE`. This solution was also used by `sybilSBML`.

### CODE REVIEW

**Comment by Waschina** [comment]
Hi  @yaccos

It's cool you made cobrar work on Windows! I tried some weeks ago but did not get very far. So your contribution is highly appreciated!

Ideally, I would like to submit the package to CRAN, and for that, the Windows compatibility would help. To this end, we need to ensure that libSBML is available on the Windows build system of CRAN. There's some info regarding adding external libraries to the Windows build system [here](https://cran.r-project.org/web/packages/external_libs.html) and [here](https://cran.r-project.org/bin/windows/base/howto-R-devel.html), but I am still unsure about how to process because the link between MXE and Rtools is not clear to me and I am not that experienced with Windows in general.

Concerning your comments:
>I could not get the package installed when the dependencies were installed in the mingw64 environment as was attempted in the main branch. The linking either failed or the symbols in the libSBML library could not be loaded. I suppose this is due to an ABI incompatibility between UCRT which is used by R and MSVCRT which is used by mingw64.

Perfect! Not sure why I specified mingw64 before.

> Currently, LIB_SBML is a hard-coded path to C:/rtools44/ucrt64. While I think it will be OK require this dependency to reside inside ucrt64, hard-coding the path does provide other problems. First, we should not expect Rtools to be located inside the root of the C: directory, while this is usually true, I think some users have other setups. Second, Rtools44 reflects that it is supposed to work with R 4.4.x, it will not work with other (and future) versions of R. I think there should be a configuration script to pick the correct Rtools directory.

I agree that this should be implemented differently. There are CRAN packages with system library dependencies. We could check how these projects handle paths and version numbers.

> Linking dynamically to a C++ API increases the risk of ABI compatibility problems compared to a C API. I don't know how big of a problem it will be in practice, but this is definately be something to watch out for.

I see. Does that refer to  glpk or libSBML, or both? 

> On Unix platforms, the libSBML dynamic library is used from its original folder, whereas on Windows it is copied into the package itself. The solution on Windows makes it easier to distribute binary packages at the cost of having a larger package size which triggers an R CMD CHECK NOTE. This solution was also used by sybilSBML.

That does not sound like the optimal solution, as the advantage of dynamic linking is a smaller package size. Ideally, libSBML will be available in future Rtools releases, and cobrar can link to libSBML there. But as I said, I am not too familiar with Windows build systems, so any contribution/hint is appreciated :)

**Comment by yaccos** [comment]
After some further exploration, I have made the following observations:

- Rtools provides its own environment for R package building in the subfolder `x86_64-w64-mingw32.static.posix` of `rtools44`. This environment operates independently of the other `msys2` environments, and packages installed in `ucrt64` are ignored by default.
- Relating to the point above, even if I remove `glpk` from `ucrt64`, `cobrar` installs just fine because it is contained inside `x86_64-w64-mingw32.static.posix`.
- In the installed package, the `cobrar.dll` file does not actually link to any dynamic library for `glpk`, although it does for `libSBML`. In the same manner, the CRAN package `Rglpk` does not link dynamically to any `glpk` library. This is because most packages inside `x86_64-w64-mingw32.static.posix`, including `glpk` link statically. Hence, the required GLPK functionality required by `cobrar` is already inside the `cobrar.dll` file.
- This type of static linking means that binary packages can be distributed to other computers without requiring systems dependencies such as `glpk` to be present.

**Comment by yaccos** [comment]
Going forward, I see these options:

- **Follow the same build process as `rsbml`**. This option requires the least amount of work and seems to be accepted by Bioconductor (and hopefully also CRAN) even though it looks ugly and require manual intervention at compile-time.
- **Rewrite `cobrar` to use `rsbml` for SBML operations**. With this option, we will kick the can down the road by offloading the dependency problems to `rsbml`. I do not know whether `rsbml` have all the capabilities we need.
- **Add `libSBML` as an upstream MXE package and make sure it is included in Rtools**. This is the most elegant solution, but it might take some time to complete. Additionally, the MXE part of Rtools does not appear to be upgraded for Rtools versions already released, so it may first appear in Rtools45 which requires R 4.5.x.
- **Include the source code of `libSBML` inside `cobrar`**. This way, `libSBML` and `cobrar` are compiled simultaneously and linked together statically. With this approach, the dependency problems vanish, but it will have the downside of longer compile times. This solution is used by some R packages such as [`rdieharder`](https://github.com/eddelbuettel/rdieharder/tree/master).

**Comment by yaccos** [comment]
Regarding, the last point, there exists a [guide](https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-libraries.pdf) for how to make such R packages. Unfortunately, I am afraid that integrating libSBML will be on the hard side of this scale.

**Comment by Waschina** [comment]
Hi @yaccos 

I still struggled installing cobrar on Windows with the approach you described above. (Perhaps I did something wrong...)

Finally, I managed it with this procedure (and the current testing branch `Waschina-windows_tests`):

1. Install libsbml using Rtools44 as you described above, also in the ucrt64 environment. `pacman -S mingw-w64-ucrt-x86_64-libsbm`
2. Open R and run the command:
```R=
library(remotes)
Sys.setenv(LIBSBML_PATH = "C:/rtools44/ucrt64")
install_github("Waschina/cobrar", ref = "Waschina-windows_tests")
```

**Comment by yaccos** [comment]
For the record @Waschina, do you know of the package `r2sbml`? It is under active development and is proposed as a Google Summer of Code project for this year (https://github.com/rstats-gsoc/gsoc2025/wiki/r2sbml-%28An-interface-to-SBML-in-R%29). Unless there are good reasons to do otherwise, I think the development of an `libSBML` in R should be focused into one package.

**Comment by Waschina** [comment]
Thanks @yaccos ! I did not know about `r2sbml`. It would be great if this develops into a full interface that is available via CRAN or Bioconductor. `cobrar` is not intended to be an interface from R to all functionalities of libSBML; it has only the connections to libsbml that are required within cobrar. I'll watch the `r2sbml` development.

**Pull request merged**
